# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_modified_type_long_text_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='secretariat',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='secretariat'),
        ),
    ]
