# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_add_secretariat_to_proyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='secretariat',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Secretar\xeda'),
        ),
    ]
