# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_secretariat_on_proyect'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='related_ticket',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ticket relacionado'),
        ),
    ]
