# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_field_added_backup_on_productionserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='requires_integration',
            field=models.BooleanField(default=False, verbose_name='requires_integration'),
        ),
    ]
