# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_applicationform_requires_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='ssh_users',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ssh_users'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='requires_integration',
            field=models.BooleanField(default=False, verbose_name='Requiere integraci\xf3n'),
        ),
    ]
