# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_add_ssh_users_to_applicationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='extra_database_users',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='extra_database_users'),
        ),
    ]
