# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_add_logs_users_to_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='extra_database_users',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuarios extras de DB'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='logs_users',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuarios Logs'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='logs_visualization',
            field=models.IntegerField(default=1, verbose_name='Modo de visualizar Logs'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='ssh_users',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuarios SSH'),
        ),
        migrations.AlterField(
            model_name='productionserver',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='testserver',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
