# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_metas_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconnectionsource',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre de usuario'),
        ),
        migrations.AddField(
            model_name='applicationconnectiontarget',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre de usuario'),
        ),
        migrations.AddField(
            model_name='productionconnectionsource',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre de usuario'),
        ),
        migrations.AddField(
            model_name='productionconnectiontarget',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre de usuario'),
        ),
    ]
