# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-19 11:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_field_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
