# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_email_on_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='url',
            field=models.URLField(default=2, max_length=300, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
