# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_add_url_to_proyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
