# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_add_field_user_to_productionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='requires_development',
            field=models.BooleanField(default=False, verbose_name='requires_development'),
        ),
    ]
