# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_applicationform_requires_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='requires_development',
            field=models.BooleanField(default=False, verbose_name='Requiere desarrollo'),
        ),
    ]
